skins_name = [
    "AK-47 | Crossfade (Factory New)",
"AK-47 | Crossfade (Field-Tested)",
"AK-47 | Crossfade (Minimal Wear)",
"AK-47 | Elite Build (Field-Tested)",
"AK-47 | Elite Build (Minimal Wear)",   
"AK-47 | Ice Coaled (Field-Tested)",
"AK-47 | Olive Polycam (Factory New)",
"AK-47 | Phantom Disruptor (Field-Tested)",
"AK-47 | Searing Rage (Field-Tested)",
"AK-47 | Slate (Field-Tested)",
"AK-47 | VariCamo Grey (Minimal Wear)",
"AK-47 | Wintergreen (Field-Tested)",
"AWP | Acheron (Minimal Wear)",
"AWP | Atheris (Field-Tested)",
"AWP | Black Nile (Field-Tested)",
"AWP | Black Nile (Minimal Wear)",
"AWP | Duality (Field-Tested)",
"AWP | Duality (Minimal Wear)",
"AWP | Mortis (Field-Tested)",
"AWP | Mortis (Minimal Wear)",
"AWP | PAW (Minimal Wear)",
"AWP | Pit Viper (Minimal Wear)",
"AWP | Worm God (Minimal Wear)",
"Desert Eagle | Corinthian (Factory New)",
"Desert Eagle | Heat Treated (Field-Tested)",
"Desert Eagle | Heat Treated (Minimal Wear)",
"Desert Eagle | Light Rail (Minimal Wear)",
"Desert Eagle | Mecha Industries (Field-Tested)",
"Desert Eagle | Meteorite (Factory New)",
"Desert Eagle | Serpent Strike (Factory New)",
"Desert Eagle | Serpent Strike (Minimal Wear)",
"Desert Eagle | Sputnik (Factory New)",
"Desert Eagle | Tilted (Factory New)",
"Desert Eagle | Tilted (Minimal Wear)",
"Desert Eagle | Trigger Discipline (Factory New)",
"Desert Eagle | Trigger Discipline (Field-Tested)",
"Desert Eagle | Trigger Discipline (Minimal Wear)",
"M4A1-S | Emphorosaur-S (Factory New)",
"M4A1-S | Emphorosaur-S (Minimal Wear)",
"M4A1-S | Night Terror (Factory New)",
"M4A1-S | Night Terror (Minimal Wear)",
"M4A1-S | Nitro (Minimal Wear)",
"M4A1-S | Wash me plz (Factory New)"
]

